config/routes.rb
Spree::Core::Engine.routes.draw do
  # solidus_auth_devise-master/config/routes.rb
  unless Spree::Auth::Config.draw_frontend_routes

    devise_for(:spree_user, {
        class_name: 'Spree::User',
        controllers: {
            sessions: 'spree/user_sessions',
            registrations: 'spree/user_registrations',
            passwords: 'spree/user_passwords',
            confirmations: 'spree/user_confirmations'
        },
        skip: [:unlocks, :omniauth_callbacks],
        path_names: { sign_in: 'login', sign_out: 'logout' },
        path: '/users'
    })

    resources :users, only: [:edit, :update]

    devise_scope :spree_user do
      get '/login', to: 'user_sessions#new', as: :login
      post '/login', to: 'user_sessions#create', as: :create_new_session
      match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
      get '/signup', to: 'user_registrations#new', as: :signup
      post '/signup', to: 'user_registrations#create', as: :registration
      get '/password/recover', to: 'user_passwords#new', as: :recover_password
      post '/password/recover', to: 'user_passwords#create', as: :reset_password
      get '/password/change', to: 'user_passwords#edit', as: :edit_password
      put '/password/change', to: 'user_passwords#update', as: :update_password
      get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
    end

    get '/checkout/registration', to: 'checkout#registration', as: :checkout_registration
    put '/checkout/registration', to: 'checkout#update_registration', as: :update_checkout_registration

    resources :account, controller: 'users'

    match '/access' => 'users#access', as: 'user_access', via: [:get]
    match '/access_login' => 'users#access_login', as: 'user_access_login', via: [:put, :post]
  end

  ##
  # Admins
  match '/admin/products/:id/erase', to: 'admin/products#erase', as: 'admin_erase_product', via: [:delete]

  ##
  # Seller
  resources :store_payment_methods
  get '/accepted_payments', to: 'store_payment_methods#index', as: 'accepted_payments'

  get '/api/option_types/:option_type_id/including_custom_option_values', to: 'spree/api/option_values#including_custom_index', as: :api_option_type_including_custom
  match '/related_option_types/:record_type/:record_id(.:format)' => 'api/option_types#related', as: :related_option_types, via: [:get, :put, :post]

  ##
  # Buyer

  resources :variants

  # Trading
  get '/orders/:id/cancel', to: 'orders#cancel', as: 'order_cancel'
  match '/checkout/update_all/:order_id', to: 'checkout#update_all', as: 'checkout_update_all', via: [:put, :post, :patch]


  get '/cart_link_dropdown', to: 'orders#cart_link_dropdown', as: 'cart_link_dropdown'

end

Rails.application.routes.draw do
  default_url_options :host => (Rails.env.production? ? 'shoppn.com' : 'localhost')

  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  #########################
  # Filtering bots
  get '/:a/:b.php', to: 'errors#not_found'
  get '/:a.php', to: 'errors#not_found'

  ####################################################
  # Admins

  resources :site_categories, path: 'admin/site_categories'

  ####################################################
  # Additions to Spree
  namespace :spree, path: '/' do
    resources :stores, only: [:show, :index]
  end

  ##
  # Users
  namespace :users do
    resources :resource_action, only: [:index, :create, :destroy]
  end

  # Buyers

  get '/sellers/:id', to: 'sellers#show', as: :seller

  # Payments
  match '/payment_notifications/log' => 'payment_notifications#log', via: [:get, :put, :post], as: 'log_payment_notification'
  resources :payment_notifications

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/spree/category_taxon.rb
module Spree
  class CategoryTaxon < Taxon

    TOP_CATEGORIES_CACHE_KEY = 'Spree::CategoryTaxon.top_categories'

    after_save :clear_cache

    def self.root
      self.where(name: 'Categories', parent_id: nil).last
    end

    ##
    # Find deepest category according to given +full_path+.
    # @return <Spree::Taxon>
    def self.find_by_full_path(full_path)
      levels = full_path.is_a?(Array) ? full_path : full_path.split(' > ')
      taxon = nil
      current_node = root
      levels.each do |cat_name|
        t = current_node.children.where(name: cat_name).first
        if t.nil?
          break
        else
          taxon = t
          current_node = t
        end
      end
      taxon
    end

    def self.find_or_create_categories_taxon()
      taxon = root
      taxon ||= ::Spree::Taxon.find_or_create_by!(taxonomy_id: find_or_create_categories_taxonomy.id) do|t|
        t.position = 0
        t.name = 'Categories'
        t.permalink = 'categories'
      end
      taxon
    end

    def self.find_or_create_categories_taxonomy()
      ::Spree::Taxonomy.find_or_create_by!(name: 'Categories') do|t|
        t.position = 1
      end
    end

    ##
    # Cached top categories.
    def self.top_categories
      Rails.cache.fetch(TOP_CATEGORIES_CACHE_KEY, expires_in: 12.hours) do
        root.children
      end
    end

    protected

    def clear_cache
      Rails.cache.delete(TOP_CATEGORIES_CACHE_KEY)
    end
  end
end

app/models/spree/country_decorator.rb
::Spree::Country.class_eval do

  def self.united_states
    @@united_states ||= where(iso:'US').first
  end

end

app/models/spree/currency_to_country.rb
module Spree
  module CurrencyToCountry
    extend ActiveSupport::Concern

    CURRENCY_TO_COUNTRY_ISO_MAP = {
        AED: %w(AE),
        AFN: %w(AF),
        ALL: %w(AL),
        AMD: %w(AM),
        ANG: %w(CW SX),
        AOA: %w(AO),
        ARS: %w(AR),
        AUD: %w(AU CX CC HM KI NR NF TV),
        AWG: %w(AW),
        AZN: %w(AZ),
        BAM: %w(BA),
        BBD: %w(BB),
        BDT: %w(BD),
        BGN: %w(BG),
        BHD: %w(BH),
        BIF: %w(BI),
        BMD: %w(BM),
        BND: %w(BN),
        BOB: %w(BO),
        BRL: %w(BR),
        BSD: %w(BS),
        BTN: %w(BT),
        BWP: %w(BW),
        BYN: %w(BY),
        BZD: %w(BZ),
        CAD: %w(CA),
        CDF: %w(CD),
        CHF: %w(LI CH),
        CLP: %w(CL),
        CNY: %w(CN),
        COP: %w(CO),
        CRC: %w(CR),
        CUC: %w(CU),
        CUP: %w(CU),
        CVE: %w(CV),
        CZK: %w(CZ),
        DJF: %w(DJ),
        DKK: %w(DK FO GL),
        DOP: %w(DO),
        DZD: %w(DZ),
        EGP: %w(EG),
        ERN: %w(ER),
        ETB: %w(ET),
        EUR: %w(FR AD AT BE CY EE FI GF TF DE GR GP VA IE IT LV LT LU MT MQ YT MC ME NL PT RE BL MF PM SM SK SI ES AX PS),
        FJD: %w(FJ),
        FKP: %w(FK),
        GBP: %w(GG IM JE GB GS),
        GEL: %w(GE),
        GHS: %w(GH),
        GIP: %w(GI),
        GMD: %w(GM),
        GNF: %w(GN),
        GTQ: %w(GT),
        GYD: %w(GY),
        HKD: %w(HK),
        HNL: %w(HN),
        HRK: %w(HR),
        HTG: %w(HT),
        HUF: %w(HU),
        IDR: %w(ID),
        ILS: %w(IL),
        INR: %w(IN BT),
        IQD: %w(IQ),
        IRR: %w(IR),
        ISK: %w(IS),
        JMD: %w(JM),
        JOD: %w(JO),
        JPY: %w(JP),
        KES: %w(KE),
        KGS: %w(KG),
        KHR: %w(KH),
        KMF: %w(KM),
        KPW: %w(KP),
        KRW: %w(KR),
        KWD: %w(KW),
        KYD: %w(KY),
        KZT: %w(KZ),
        LAK: %w(LA),
        LBP: %w(LB),
        LKR: %w(LK),
        LRD: %w(LR),
        LSL: %w(LS),
        LYD: %w(LY),
        MAD: %w(MA EH),
        MDL: %w(MD),
        MGA: %w(MG),
        MKD: %w(MK),
        MMK: %w(MM),
        MNT: %w(MN),
        MOP: %w(MO),
        MRO: %w(MR),
        MUR: %w(MU),
        MVR: %w(MV),
        MWK: %w(MW),
        MXN: %w(MX),
        MYR: %w(MY),
        MZN: %w(MZ),
        NAD: %w(NA),
        NGN: %w(NG),
        NIO: %w(NI),
        NOK: %w(BV NO SJ),
        NPR: %w(NP),
        NZD: %w(CK NZ NU PN TK),
        OMR: %w(OM),
        PAB: %w(PA),
        PEN: %w(PE),
        PGK: %w(PG),
        PHP: %w(PH),
        PKR: %w(PK),
        PLN: %w(PL),
        PYG: %w(PY),
        QAR: %w(QA),
        RON: %w(RO),
        RSD: %w(RS),
        RUB: %w(RU),
        RWF: %w(RW),
        SAR: %w(SA),
        SBD: %w(SB),
        SCR: %w(SC),
        SDG: %w(SD),
        SEK: %w(SE),
        SGD: %w(SG),
        SHP: %w(SH),
        SLL: %w(SL),
        SOS: %w(SO),
        SRD: %w(SR),
        SSP: %w(SS),
        STD: %w(ST),
        SVC: %w(SV),
        SYP: %w(SY),
        SZL: %w(SZ),
        THB: %w(TH),
        TJS: %w(TJ),
        TMT: %w(TM),
        TND: %w(TN),
        TOP: %w(TO),
        TRY: %w(TR),
        TTD: %w(TT),
        TWD: %w(TW),
        TZS: %w(TZ),
        UAH: %w(UA),
        UGX: %w(UG),
        USD: %w(US HT PA SV AS BQ IO VG EC GU MH FM MP PW PR TL TC UM VI AQ PS),
        UYU: %w(UY),
        UZS: %w(UZ),
        VEF: %w(VE),
        VND: %w(VN),
        VUV: %w(VU),
        WST: %w(WS),
        XAF: %w(CM CF TD CG GQ GA),
        XCD: %w(AI AG DM GD MS KN LC VC),
        XOF: %w(BJ BF CI GW ML NE SN TG),
        XPF: %w(PF NC WF),
        YER: %w(YE),
        ZAR: %w(LS NA ZA),
        ZMW: %w(ZM),
        ZWL: %w(ZW),
    }
  end
end

app/models/spree/custom_option_value.rb
module Spree
  class CustomOptionValue < Spree::Base
    belongs_to :option_type, class_name: 'Spree::OptionType', inverse_of: :option_values
    acts_as_list scope: :option_type
  end
end

app/models/spree/gateway/pay_pal_gateway_decorator.rb
Spree::Gateway::PayPalGateway.class_eval do
  attr_accessor :payment_method_id
end

app/models/spree/image_decorator.rb
module Spree
  Image.class_eval do

  end
end

app/models/spree/line_item_decorator.rb
Spree::LineItem.class_eval do
  belongs_to :product

  before_save :set_references

  private

  def set_references
    self.product_id = variant.product_id
  end
end

app/models/spree/option_type_decorator.rb
module Spree
  OptionType.class_eval do
    validate :check_name

    VALID_OPTION_NAME_REGEX = /^((max|maximum|minmum|min|average|avg|estimate|est|US|UK|original|market|man'?s?|men'?s?|woman'?s?|women'?s?|kids?|adults?|new|supported|product|item)\s+)?([a-z]{2,}\s+)?(types?|category|name|colou?rs?|sizes?|number|no|sku|brand|width|length|height|diameter|radius|thickness|area|waist|bust|collar|weight|depth|models?|material|fabric|quality|quantity|count|pieces?|style|group|range|age|gender|level|class|capacity|time|date|life|season|quantity|version|edition|mode|port|payment|pattern|price|cost|charge|fee|rate|frequency|response|speed|bandwidth|volume|shape|method|current|voltage|percentage|ratio|frequency|condition|code|sleeve|sensitivity|grade|rating|platform|protocol|operating\s+system|format|angle|interface|standard)$/i

    DEFAULT_CACHE_KEY = 'DEFAULT_OPTION_TYPES'
    DEFAULT_OPTION_NAMES = ['color', 'clothing color', 'size', 'clothing size', 'shoe size']
    CATEGORY_NAMES_TO_OPTION_TYPE_NAMES_MAP = {
      /shoes?\s*\z/i => ['color', 'clothing color', 'shoe size'],
      /clothing|clothes/i => ['color', 'clothing color', 'size', 'clothing size']
    }

    after_save :clear_cache

    ##
    # @specific_user <Spree::User> If specified, would be option_values only accessible_by that.
    def as_json_with_option_values(specific_user = nil)
      json = as_json(except: [:created_at, :updated_at])
      list = specific_user ? option_values.accessible_by(::Spree::Ability.new(specific_user))
        : option_values.for_public
      json[:option_values] = list.collect{|v| v.as_json(except:[:created_at, :updated_at] ) }
      json
    end

    def self.valid_option_name?(name = '')
      !name.to_sanitized_keyword_name.match(VALID_OPTION_NAME_REGEX).nil?
    end

    ##
    # Iterates over list of category names, and find matches and their paired option type names
    # @category_names <Array of String>
    def self.default_option_types(category_names = [])
      option_names = Set.new
      category_names.each do|category_name|
        CATEGORY_NAMES_TO_OPTION_TYPE_NAMES_MAP.each_pair do|k, v|
          option_names += v if k =~ category_name
        end
      end
      self.where(name: option_names.to_a )
    end

    protected

    def check_name
      unless self.class.valid_option_name?(name)
        self.errors.add(:name)
      end
    end

    def clear_cache
      Rails.cache.delete(DEFAULT_CACHE_KEY)
    end
  end
end

app/models/spree/option_value_decorator.rb
module Spree
  OptionValue.class_eval do

    attr_accessor :variant_ids

    belongs_to :user, class_name: 'Spree::User', foreign_key: :user_id

    scope :with_names, lambda {|option_type_names|
        joins(:option_type).where("#{Spree::OptionType.table_name}.name IN (?)", option_type_names ) }
    scope :single_names, -> { where("name NOT LIKE '%/%' AND name NOT LIKE '% %'") }
    scope :multi_word_names, -> { where("name LIKE '%/%' OR name LIKE '% %'") }
    scope :for_public, -> { where(user_id: nil) }

    # cancan.accessible_by is different
    scope :manageable_by, lambda {|user_id| joins(:option_type).where('user_id IS NULL OR user_id=?', user_id) }

    def self.accessible_by(ability, action = :index)
      self.manageable_by(ability.user.try(:id) )
    end

    def option_type_name
      option_type.try(:name)
    end

    def option_type_presentation
      option_type.try(:presentation)
    end
  end
end

app/models/spree/order_decorator.rb
::Spree::Order.class_eval do

  before_save :generate_transaction_code

  ###############################
  # Overrides

  def finalize!
    ::Jobs::OrderJob.perform_async(id)
    super
  end

  ###############################
  # New methods

  ##
  # If +which_payment+ not given, would be latest payment w/ checkout state.
  def forward_to_process_payment?(which_payment = nil)
    which_payment ||= payments.checkout.last
    return false if which_payment.nil?

    which_payment.payment_method.is_a?(Spree::PaymentMethod::PayPal)
  end

  ##
  # @return <Spree::PaymentMethod>
  def payment_method_to_forward
    payments.checkout.last.try(:payment_method)
  end

  ##
  # 7-characters, alphanumeral.
  def self.random_transaction_code(id = nil)
    ( ( (id || rand(1000)) % 5) * 243 + rand(5987123654) ).to_s(36).rjust(7,'0').upcase
  end

  private

  def allow_cancel?
    return false unless (state == 'payment' || state == 'confirm' || completed? ) && state != 'canceled'
    shipment_state.nil? || %w{ready backorder pending}.include?(shipment_state)
  end

  def generate_transaction_code
    self.transaction_code = self.class.random_transaction_code(id) if transaction_code.blank?
  end

end

app/models/spree/payment_method/apple_pay.rb
module Spree
  class PaymentMethod::ApplePay < PaymentMethod

  end
end

app/models/spree/payment_method/credit_card_decorator.rb
::Spree::PaymentMethod::CreditCard.class_eval do

  def gateway_class
    # TODO:
  end

  def account_reference_label
    I18n.t('spree.card_number')
  end
end

app/models/spree/payment_method/google_pay.rb
module Spree
  class PaymentMethod::GooglePay < PaymentMethod

  end
end

app/models/spree/payment_method/pay_pal.rb
module Spree
  class PaymentMethod::PayPal < PaymentMethod
    def payment_source_class
      Spree::Gateway::PayPalGateway
    end

    def supports?(source)
      true
    end

    def source_required?
      false
    end

    def forward_payment_url

    end

  end
end

app/models/spree/payment_method_decorator.rb
Spree::PaymentMethod.class_eval do
  def self.populate_with_common_payment_methods
    ::Spree::PaymentMethod::PayPal.find_or_create_by(name: 'PayPal') do|pm|
      pm.description ='Pay with PayPal'
      pm.active = true
      pm.position = 1
      pm.available_to_users = true
    end
    ::Spree::PaymentMethod::CreditCard.find_or_create_by(name: 'Credit Card, Visa/MasterCard') do|pm|
      pm.description = 'Pay with credit cards like Visa or MasterCard'
      pm.active = true
      pm.position = 2
      pm.available_to_users = true
    end
    ::Spree::PaymentMethod::ApplePay.find_or_create_by(name: 'Apple Pay') do|pm|
      pm.description = 'Pay with ApplePay'
      pm.active = true
      pm.position = 3
      pm.available_to_users = true
    end
    ::Spree::PaymentMethod::GooglePay.find_or_create_by(name: 'Google Pay') do|pm|
      pm.description = 'Pay with GooglePay'
      pm.active = true
      pm.position = 4
      pm.available_to_users = true
    end
  end

  ##
  # Depending on payment method type, the attribute name that payer can refer to during payments;
  # for example, credit card needs 'card number' while PayPal simply needs 'Account ID'.
  def account_reference_label
    I18n.t('spree.account_id')
  end

  def forward_payment_url
    nil
  end
end

app/views/spree/checkout/_address.html.erb
<div class="columns alpha six" data-hook="billing_fieldset_wrapper">
  <fieldset id="billing" data-hook>
    <%= form.fields_for :bill_address do |bill_form| %>
      <legend align="center"><%= t('spree.billing_address') %></legend>
      <%= render partial: 'spree/address/form', locals: { form: bill_form, address_type: 'billing', address: @order.bill_address } %>
    <% end %>
  </fieldset>
</div>

<div class="columns omega six" data-hook="shipping_fieldset_wrapper">
  <fieldset id="shipping" data-hook>
    <%= form.fields_for :ship_address do |ship_form| %>
      <legend align="center"><%= t('spree.shipping_address') %></legend>
      <div class="checkbox" data-hook="use_billing">
        <%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address? %>
        <%= label_tag :order_use_billing, t('spree.use_billing_address'), id: 'use_billing' %>
      </div>
      <%= render partial: 'spree/address/form', locals: { form: ship_form, address_type: 'shipping', address: @order.ship_address } %>
    <% end %>
  </fieldset>
</div>
<hr class="clear" />

<div class="form-buttons" data-hook="buttons">
  <%= submit_tag t('spree.save_and_continue'), class: 'continue button primary' %>
  <% if try_spree_current_user %>
    <span data-hook="save_user_address">
      &nbsp; &nbsp;
      <%= check_box_tag 'save_user_address', '1', try_spree_current_user.respond_to?(:persist_order_address) %>
      <%= label_tag :save_user_address, t('spree.save_my_address') %>
    </span>
  <% end %>
</div>

app/views/spree/checkout/_confirm.html.erb
<fieldset id="order_details" data-hook>
  <div class="clear"></div>
  <legend align="center"><%= t('spree.confirm') %></legend>
  <%= render partial: 'spree/shared/order_details', locals: { order: @order } %>
</fieldset>

<br />

<div class="form-buttons" data-hook="buttons">
  <% Spree::Frontend::Config[:require_terms_and_conditions_acceptance].tap do |requires_acceptance| %>
    <% if requires_acceptance %>
      <div class="terms_and_conditions" data-hook="terms_and_conditions">
        <div class="policy"><%= render partial: "spree/checkout/terms_and_conditions" %></div>
        <%= check_box_tag :accept_terms_and_conditions, 'accepted', false %>
        <%= label_tag :accept_terms_and_conditions, t('spree.agree_to_terms_of_service') %>
      </div>
    <% end %>

    <%= submit_tag t('spree.place_order'),
      disabled: requires_acceptance,
      class: "continue button primary #{ 'disabled' if requires_acceptance }" %>
  <% end %>

  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/_coupon_code.html.erb
<div class="coupon-code" data-hook='coupon_code'>
  <%= form_for order, url: update_checkout_path(order.state) do |form| %>
    <%= form.label :coupon_code %>
    <%= form.text_field :coupon_code, placeholder: true %>

    <button type="submit" class="button coupon-code-apply-button" id="coupon-code-apply-button">
      <%= t('spree.apply_code') %>
    </button>
  <% end %>

  <div id='coupon_status'></div>
</div>

app/views/spree/checkout/_delivery.html.erb
<fieldset id='shipping_method' data-hook>
  <legend align="center"><%= t('spree.delivery') %></legend>
  <div class="inner" data-hook="shipping_method_inner">
    <div id="methods">
      <%= form.fields_for :shipments do |ship_form| %>

        <div class="shipment">
          <h3 class="stock-location" data-hook="stock-location">
            <%= t('spree.package_from') %>
            <strong class="stock-location-name" data-hook="stock-location-name"><%= ship_form.object.stock_location.name %></strong>
          </h3>

          <table class="stock-contents" data-hook="stock-contents">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= t('spree.item') %></th>
              <th><%= t('spree.qty') %></th>
              <th><%= t('spree.price') %></th>
            </thead>
            <tbody>
              <% ship_form.object.manifest.each do |item| %>
                <tr class="stock-item">
                  <td class="item-image">
                    <%= render 'spree/shared/image',
                      image: (item.variant.gallery.images.first || item.variant.product.gallery.images.first),
                      size: :mini %>
                  </td>
                  <td class="item-name"><%= item.variant.name %></td>
                  <td class="item-qty"><%= item.quantity %></td>
                  <td class="item-price"><%= display_price(item.variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <h5 class="stock-shipping-method-title"><%= t('spree.shipping_method') %></h5>
          <ul class="radios shipping-methods">
            <% ship_form.object.shipping_rates.each do |rate| %>
              <li class="shipping-method">
                <label>
                  <%= ship_form.radio_button :selected_shipping_rate_id, rate.id %>
                  <span class="rate-name"><%= rate.name %></span>
                  <span class="rate-cost"><%= rate.display_cost %></span>
                </label>
              </li>
            <% end %>
          </ul>
        </div>

      <% end %>

      <% if @differentiator.try(:missing?) %>
        <div class="shipment unshippable">
          <h3 class="stock-location" data-hook="stock-location">
            <%= t('spree.unshippable_items') %>
          </h3>
          <table class="stock-contents" data-hook="stock-missing">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= t('spree.item') %></th>
              <th><%= t('spree.qty') %></th>
              <th><%= t('spree.price') %></th>
            </thead>
            <tbody>
              <% @differentiator.missing.each do |variant, quantity| %>
                <tr class="stock-item">
                  <td class="item-image">
                    <%= render 'spree/shared/image',
                      image: (variant.gallery.images.first || variant.product.gallery.images.first),
                      size: :mini %>
                  </td>
                  <td class="item-name"><%= variant.name %></td>
                  <td class="item-qty"><%= quantity %></td>
                  <td class="item-price"><%= display_price(variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>

    </div>
    <% if Spree::Config[:shipping_instructions] %>
      <p id="minstrs" data-hook>
        <%= form.label :special_instructions, t('spree.shipping_instructions') %><br />
        <%= form.text_area :special_instructions, cols: 40, rows: 7 %>
      </p>
    <% end %>
  </div>
</fieldset>

<br />

<div class="form-buttons" data-hook="buttons">
  <%= submit_tag t('spree.save_and_continue'), class: 'continue button primary' %>
</div>

app/views/spree/checkout/_order_line_item_entry.html.haml
:ruby
  # Similar to frontend/app/views/spree/orders/_line_item.html.erb
  # Expected locals:
  #   line_item <Spree::LineItem>
  variant = line_item.variant
- if variant
  .line-item
    .cart-item-image.item-field
      = link_to(render('spree/shared/image', image: (variant.gallery.images.first || variant.product.gallery.images.first), size: :small), variant.product)
    .cart-item-description.item-field
      %h6 
        = link_to line_item.name.truncate(40), product_path(variant.product)
      %span.option-text
        = variant.options_text
      - if line_item.insufficient_stock?
        %span.out-of-stock 
          = t('spree.out_of_stock')
    .cart-item-price.item-field
      %h4
        = line_item.quantity.to_s + ' X' unless line_item.quantity < 2
        = line_item.money.to_html
      %span.shipping-fee.text-right='+ $4.35 shipping'

app/views/spree/checkout/_payment.html.erb
<fieldset id="payment" data-hook>
  <legend align="center"><%= t('spree.payment_information') %></legend>
  <div data-hook="checkout_payment_step">
    <% if @wallet_payment_sources.present? %>
      <div class="card_options">
        <%= radio_button_tag 'use_existing_card', 'yes', true %>
        <label for="use_existing_card_yes">
          <%= t('spree.use_existing_cc') %>
        </label>
        <br/>
        <%= radio_button_tag 'use_existing_card', 'no' %>
        <label for="use_existing_card_no">
          <%= t('spree.use_new_cc_or_payment_method') %>
        </label>
      </div>

      <div id="existing_cards">
        <div class="field" data-hook="existing_cards">
          <table class="existing-credit-card-list">
            <tbody>
              <% @wallet_payment_sources.each do |wallet_payment_source| %>
                <%=
                  render(
                    partial: "spree/checkout/existing_payment/#{wallet_payment_source.payment_source.payment_method.partial_name}",
                    locals: {
                      wallet_payment_source: wallet_payment_source,
                      default: wallet_payment_source == @default_wallet_payment_source,
                    }
                  )
                %>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    <% end %>

    <div id="payment-method-fields" data-hook>
      <% @order.available_payment_methods.each do |method| %>
      <p>
        <label>
          <%= radio_button_tag "order[payments_attributes][][payment_method_id]", method.id, method == @order.available_payment_methods.first %>
          <%= t(method.name, scope: 'spree.payment_methods', default: method.name) %>
        </label>
      </p>
      <% end %>
    </div>

    <ul id="payment-methods" data-hook>
      <% @order.available_payment_methods.each do |method| %>
        <li id="payment_method_<%= method.id %>" class="<%= 'last' if method == @order.available_payment_methods.last %>" data-hook>
          <fieldset>
            <%= render partial: "spree/checkout/payment/#{method.partial_name}", locals: { payment_method: method } %>
          </fieldset>
        </li>
      <% end %>
    </ul>
    <br style="clear:both;" />
  </div>
</fieldset>

<br class="space" />

<div class="form-buttons" data-hook="buttons">
  <%= submit_tag t('spree.save_and_continue'), class: 'continue button primary' %>
  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/_terms_and_conditions.en.html.erb
Put your terms and conditions here