config/routes.rb
Spree::Core::Engine.routes.draw do
  # solidus_auth_devise-master/config/routes.rb
  unless Spree::Auth::Config.draw_frontend_routes

    devise_for(:spree_user, {
        class_name: 'Spree::User',
        controllers: {
            sessions: 'spree/user_sessions',
            registrations: 'spree/user_registrations',
            passwords: 'spree/user_passwords',
            confirmations: 'spree/user_confirmations'
        },
        skip: [:unlocks, :omniauth_callbacks],
        path_names: { sign_in: 'login', sign_out: 'logout' },
        path: '/users'
    })

    resources :users, only: [:edit, :update]

    devise_scope :spree_user do
      get '/login', to: 'user_sessions#new', as: :login
      post '/login', to: 'user_sessions#create', as: :create_new_session
      match '/logout', to: 'user_sessions#destroy', as: :logout, via: Devise.sign_out_via
      get '/signup', to: 'user_registrations#new', as: :signup
      post '/signup', to: 'user_registrations#create', as: :registration
      get '/password/recover', to: 'user_passwords#new', as: :recover_password
      post '/password/recover', to: 'user_passwords#create', as: :reset_password
      get '/password/change', to: 'user_passwords#edit', as: :edit_password
      put '/password/change', to: 'user_passwords#update', as: :update_password
      get '/confirm', to: 'user_confirmations#show', as: :confirmation if Spree::Auth::Config[:confirmable]
    end

    get '/checkout/registration', to: 'checkout#registration', as: :checkout_registration
    put '/checkout/registration', to: 'checkout#update_registration', as: :update_checkout_registration

    resources :account, controller: 'users'

    match '/access' => 'users#access', as: 'user_access', via: [:get]
    match '/access_login' => 'users#access_login', as: 'user_access_login', via: [:put, :post]
  end

  ##
  # Admins
  match '/admin/products/:id/erase', to: 'admin/products#erase', as: 'admin_erase_product', via: [:delete]

  ##
  # Seller
  resources :store_payment_methods
  get '/accepted_payments', to: 'store_payment_methods#index', as: 'accepted_payments'

  get '/api/option_types/:option_type_id/including_custom_option_values', to: 'spree/api/option_values#including_custom_index', as: :api_option_type_including_custom
  match '/related_option_types/:record_type/:record_id(.:format)' => 'api/option_types#related', as: :related_option_types, via: [:get, :put, :post]

  ##
  # Buyer

  resources :variants

  # Trading
  get '/orders/:id/cancel', to: 'orders#cancel', as: 'order_cancel'
  match '/checkout/update_all/:order_id', to: 'checkout#update_all', as: 'checkout_update_all', via: [:put, :post, :patch]


  get '/cart_link_dropdown', to: 'orders#cart_link_dropdown', as: 'cart_link_dropdown'

end

Rails.application.routes.draw do
  default_url_options :host => (Rails.env.production? ? 'shoppn.com' : 'localhost')

  # This line mounts Solidus's routes at the root of your application.
  # This means, any requests to URLs such as /products, will go to Spree::ProductsController.
  # If you would like to change where this engine is mounted, simply change the :at option to something different.
  #
  # We ask that you don't use the :as option here, as Solidus relies on it being the default of "spree"
  mount Spree::Core::Engine, at: '/'

  #########################
  # Filtering bots
  get '/:a/:b.php', to: 'errors#not_found'
  get '/:a.php', to: 'errors#not_found'

  ####################################################
  # Admins

  resources :site_categories, path: 'admin/site_categories'

  ####################################################
  # Additions to Spree
  namespace :spree, path: '/' do
    resources :stores, only: [:show, :index]
  end

  ##
  # Users
  namespace :users do
    resources :resource_action, only: [:index, :create, :destroy]
  end

  # Buyers

  get '/sellers/:id', to: 'sellers#show', as: :seller

  # Payments
  match '/payment_notifications/log' => 'payment_notifications#log', via: [:get, :put, :post], as: 'log_payment_notification'
  resources :payment_notifications

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/retail/product.rb
require 'csv'
require 'open-uri'

class Retail::Product < ::RetailScraperRecord

  self.table_name = 'retail_products'

  attr_accessor :temp_specs, :categories_object

  validates_presence_of :retail_site_id, :title

  INVALID_TITLE_REGEXP = /\A(301|302|404|500)\s+Moved\s+Permanently/i

  validates :title, format: { without: INVALID_TITLE_REGEXP }

  ################################
  # Scopes

  belongs_to :retail_site, class_name: 'Retail::Site', foreign_key: :retail_site_id
  belongs_to :retail_store, class_name: 'Retail::Store', foreign_key: :retail_store_id, optional: true
  belongs_to :page, class_name: 'Scraper::Page', foreign_key: :scraper_page_id, optional: true
  alias_method :scraper_page, :page

  has_many :product_specs, class_name: 'Retail::ProductSpec', foreign_key: :retail_product_id, dependent: :delete_all
  alias_method :specs, :product_specs
  has_many :product_photos, class_name: 'Retail::ProductPhoto', foreign_key: :retail_product_id, dependent: :destroy
  alias_method :photos, :product_photos

  has_many :migrations, class_name: 'Retail::ProductToSpreeProduct', foreign_key: :retail_product_id
  has_many :spree_products, class_name: 'Spree::Product', through: :migrations, foreign_key: :spree_product_id

  ##################################
  # Callbacks

  before_save :convert_attributes
  before_destroy :reset_assets!

  def store_id
    retail_store.try(:retail_site_store_ids)
  end

  def category_names
    (JSON.load(categories) || []).collect { |h| h['name'] }
  rescue JSON::ParserError
    []
  end

  def other_site_categories
    ::Retail::OtherSiteCategory.find_for_retail_product(self)
  end

  def leaf_other_site_category
    other_site_categories.last
  end

  ##
  # Deepest level of category, dependent on categories property specifying the category path.
  # @return <SiteCategory>
  def leaf_site_category
    categories.present? ? ::SiteCategory.find_by_full_path(retail_site.name, category_names) : []
  end
  alias_method :site_category, :leaf_site_category

  # Mixed spec name and values together, w/ spec.name as its own attribute name, e.g., "max_size": 10
  def specs_list
    # product_specs.collect{|spec| [spec.name, spec.value_1, spec.value_2].compact }.flatten.uniq Mixed spec name and values together
    product_specs.collect { |spec| { spec.name_as_key => spec.value_1} }
  end

  def as_json(options = {})
    h = super(options)
    # h['specs'] = product_specs.collect(&:as_json)
    # h['product_photos'] = product_photos.collect(&:as_json)
    h
  end

  ##
  # Grouped up list of values by common spec name.
  # @return <Hash of String => Set of values>
  def spec_name_to_values_group(which_product_specs = nil)
    h = {}
    (which_product_specs || self.product_specs).each do|spec|
      set = h[spec.name] || Set.new
      set << spec.object_value
      h[spec.name] = set
    end
    h
  end

  ###############################
  # Util methods

  ##
  # Destroys product_photos and product_specs
  def reset_assets!
    self.product_photos.each(&:destroy)
    self.product_specs.each(&:destroy)
  end

  ##
  # Delete duplicate specs.
  def clean_product_specs!
    existing_specs = Set.new
    product_specs.each do |spec|
      if existing_specs.include?(spec.value_for_comparison)
        puts "  - #{spec}"
        spec.destroy
      else
        existing_specs << spec
      end
    end
  end

  ##
  # Find or create this retail store
  def connect_to_retail_store!(retail_site_id, retail_site_store_id, other_attr = {})
    store = ::Retail::Store.find_or_create_by!(
        retail_site_id: retail_site_id, retail_site_store_id: retail_site_store_id) do|record|
      record.attributes = other_attr if other_attr.size > 0
    end
    self.retail_store ||= store
    self.save
  end

  ##
  # Matched or created ProductSpec would be yielded in block.
  # @specs <Array of Retail::ProductSpec or a Hash w/ spec name to value >
  # @return <Array of Retail::ProductSpec> updated list
  #
  def find_or_create_product_specs!(specs, &block)
    matching_specs = []
    group = self.product_specs.group_by(&:name)
    logger.info "  \\ given specs #{specs}"
    (specs || [] ).each do|obj|
      _name = nil
      _value = nil
      if obj.is_a?(::Retail::ProductSpec)
        _name = obj.name
        _value = obj.object_value
      elsif obj.is_a?(Hash)
        # model hash format like [{"name"=>"available sizes", "value_1"=>"S M"}, {"name"=>"available colors", "value_1"=>""}]
        obj_stringified = obj.stringify_keys
        sorted_keys = obj_stringified.keys.sort
        if sorted_keys == %w{name value_1}
          _name = obj_stringified['name']
          _value = obj_stringified['value_1']
        else # dynamic keys to values: 'material' => 'wool', 'color' => 'black'
          _name = obj_stringified.keys.first
          _value = obj_stringified[_name]
        end
      end
      next if _name.blank?
      # is new
      cur_set = group[_name] || []
      if (cur_spec = cur_set.find{|_spec| [_spec.value_1, _spec.value_2] == [_value, nil] } )
        matching_specs << cur_spec
      else
        cur_spec = Retail::ProductSpec.create(retail_product_id: id, name: _name, value_1: _value)
        matching_specs << cur_spec
      end
      yield cur_spec if block_given?
    end
    matching_specs
  end

  def fix_product_categories!
    self.update_attributes(categories: retail_site.scraper.find_categories_object(page.make_mechanize_page).to_json)
  end

  ##
  # @return <Spree::Product>
  def create_as_spree_product(force_recreate = false, other_attributes = {}, &block)
    product = force_recreate ? nil : ::Retail::ProductToSpreeProduct.where(retail_product_id: id).first.try(:spree_product)
    spree_user = retail_store ? retail_store.setup_spree_user_and_store! : nil
    unless product
      product = self.class.make_spree_product(self)
      product.attributes = other_attributes if other_attributes.size > 0
      product.user_id ||= spree_user.id
      product.save
      ::Retail::ProductToSpreeProduct.create(retail_product_id: id, spree_product_id: product.id)
      product.copy_images_from_retail_product!(self)
      product.create_categories_taxon!(self)
      product.copy_product_specs_from_retail_product!(self)
    end
    yield product if block_given?
    product
  end

  ##
  # @retail_product <Retail::Product> new but not saved
  def self.make_spree_product(retail_product)
    product = ::Spree::Product.new(
        name: retail_product.title.strip,
        description: retail_product.description,
        available_on: Time.now,
        shipping_category_id: ::Spree::ShippingCategory.default.try(:id),
        price: retail_product.price
      )
    product
  end

  protected

  def convert_attributes
    if categories_object.is_a?(Hash)
      self.categories = categories_object.to_json
    end
    self.description = description.encode_to_utf8 if description
  end

end

app/views/spree/admin/products/_form_in_one.html.haml
:ruby
  prices = @product.master.try(:prices).try(:order, 'id asc') || []
  left_over_isos = Spree::Config.available_currencies.map(&:iso_code) - prices.collect{|p| p.country_iso }

= hidden_field_tag(:form, params[:form])
= f.hidden_field(:master_product_id)
= f.hidden_field(:shipping_category_id, value: ::Spree::ShippingCategory.default.try(:id) || 1 )
= f.hidden_field(:tax_category_id, value: ::Spree::TaxCategory.default.try(:id) || 1 )
-#%legend(align="center") #{t('spree.product_info')}
%div(data-hook="admin_product_form_fields")
  .row
    %div(class="left col-8" data-hook="admin_product_form_left")
      - if (@master_product)
        .box-shadow.box-body
          %center
            %h1
              Can you beat
              %span.yellow='$' + @master_product.price.to_s
              shipped?
            %span='392 buyers will be notified of this listing if you beat that price!'
      %div.box-shadow.box-body.mt-4(data-hook="admin_product_form_price")
        .d-flex
          %span
            = f.label :price, class: Spree::Config.require_master_price ? 'required' : '' do
              = 'Your Price' #t('spree.price')
            %br/
            %a(href="#" onclick="addCurrencyPriceField()" class="fa fa-plus float-right")

          .col-10
            #curreny_prices_list.d-flex.f-wrap
              - prices.each_with_index do|price, price_idx|
                .col-6.mb-2
                  = render partial: 'spree/admin/shared/currency_price_form', locals: { f: f, price: price, currency_isos: left_over_isos }
              .col-6.mb-2
                = render partial: 'spree/admin/shared/currency_price_form', locals: { f: f, price: ::Spree::Price.new(country_iso: left_over_isos.first, amount: prices.blank? ? @product.price : nil), currency_isos: left_over_isos, required: prices.size.zero? }
                = f.error_message_on :price
              #new_currency_price_wrapper(style="display:none;")
                = render partial: 'spree/admin/shared/currency_price_form', locals: { f: f, price: ::Spree::Price.new(country_iso: left_over_isos.first, amount: prices.blank? ? @product.price : nil), currency_isos: left_over_isos }
      .box-shadow.box-body.mt-4
        %div(data-hook="admin_product_form_name")
          = f.field_container :name do
            = f.label :name, 'Product Title', class: 'required'
            = f.text_field :name, class: 'fullwidth title', required: true
            = f.error_message_on :name
        %div(data-hook="admin_product_form_description")
          = f.field_container :description do
            = f.label :description
            = f.text_area :description, {rows: "#{unless @product.has_variants? then '22' else '15' end}", class: 'fullwidth'}
            = f.error_message_on :description
        %div(data-hook="admin_product_form_category")
          = f.field_container :taxons do
            = f.label :category, 'Category'
            = select_tag('product[taxon_ids]', options_from_collection_for_select(::Spree::CategoryTaxon.top_categories, 'id', 'name', @product.taxon_ids ), id: 'product_category', class: 'form-control' )
          = link_to('Option Types 2', related_option_types_path(record_type:'taxon',record_id: ::Spree::Taxon.under_categories.where(name:'Clothing').first.id, format:'json', token: spree_current_user.try(:spree_api_key) ), method: :get, class:'btn btn-secondary hidden')

      %div.hidden(data-hook="admin_product_form_taxons")
        = f.field_container :taxons do
          = f.label :taxon_ids, plural_resource_name(Spree::Taxon)
          %br/
      %div(data-hook="admin_product_form_meta" class="hidden")
        %div(data-hook="admin_product_form_meta_title")
          = f.field_container :meta_title do
            = f.label :meta_title
            = f.text_field :meta_title, class: 'fullwidth'
        %div(data-hook="admin_product_form_meta_keywords")
          = f.field_container :meta_keywords do
            = f.label :meta_keywords
            = f.text_field :meta_keywords, class: 'fullwidth'
        %div(data-hook="admin_product_form_meta_description")
          = f.field_container :meta_description do
            = f.label :meta_description
            = f.text_field :meta_description, class: 'fullwidth'

      .box-shadow.mt-4.p-3.ps-rel(data-hook="admin_product_form_variants")
        = render partial: 'product_variant'
        = render partial: 'color_picker'
      .box-shadow.mt-4.pt-3.pr-3.pl-3.pb-0(data-hook="admin_product_form_sizes")
        = render partial: 'product_sizes', locals: { f: f }

      .box-shadow.mt-4.pt-3.pr-3.pl-3(data-hook="admin_product_form_shipping")
        %div(data-hook="admin_product_shipping_standard")
          = f.field_container :shipping_standard do
            %label(for="product_shipping_standard")= 'Approximate Standard Shipping Time'
            %input#shipping_standard.fullwidth(type="text")
        %div(data-hook="admin_product_shipping_expedite")
          = f.field_container :shipping_expedite do
            %label(for="shipping_standard_expedite")= "Approximate Expedite Shipping Time"
            %input#shipping_standard_expedite.fullwidth(type="text")

      %br/
      %fieldset.no-border-bottom
        %legend(align="center") #{t('spree.main_images')}
        %table(id="main_images_table" class="table index sortable inline-editable-table" data-hook="images_table" data-sortable-link="#{@product.try(:id) ? update_positions_admin_product_images_path(@product) : ''}" )
          %colgroup
            %col(style="width: 5%")
            %col(style="width: 10%")
            - if @product.has_variants?
              %col(style="width: 40%")
            %col(style="width: 30%")
            %col(style="width: 15%")

          %thead
            %tr(data-hook="images_header")
              %th
              %th #{ t('spree.thumbnail') }
              - if @product.has_variants?
                %th #{ Spree::Variant.model_name.human }
              %th #{ Spree::Image.human_attribute_name(:alt) }
              %th(class="actions")

          %tbody
            - if @product.gallery.images.size > 0
              = render partial: 'spree/admin/images/image_row', collection: @product.gallery.images, as: :image
            - else
              %tr(id="new_product_image_row_0")
                = render partial: 'product_upload_image', locals: { f: f, row_id: 'new_product_image_row_0' }
            = render partial: 'product_upload_image', locals: { f: f, row_id: 'new_product_image_row' }
        .pull-right
          %button(type='button' class='btn btn-secondary' onclick="addMoreProductImageRow()") More Image
      - if false && @product.id
        %br/
        %fieldset.no-border-bottom
          %legend(align="center") #{t('spree.variants')}
          %table(class="table index sortable inline-editable-table" data-sortable-link="#{update_positions_admin_product_variants_path(@product) }")
            %colgroup
              %col(style="width: 5%")
              %col(style="width: 50%")
              %col(style="width: 30%")
              %col(style="width: 15%")
            %thead(data-hook="variants_header")
              %tr
                %th
                %th #{t('spree.options') }
                %th #{ Spree::Variant.human_attribute_name(:price) }, #{ Spree::Variant.human_attribute_name(:sku) }
                %th.actions
            %tbody
              = render partial: 'product_variant_row', collection: @product.variants, as: :variant, locals: { product: @product }

          .pull-right
            = link_to(t('spree.new_variant'), new_admin_product_variant_path([@product] ), class:'btn btn-secondary' )
      %br/
      %fieldset.no-border-bottom
        %legend(align="center") #{ plural_resource_name(Spree::ProductProperty) }
        .add_product_properties(data-hook="add_product_properties")/
        %table(id="product_properties_table" class="index #{@product.try(:id) ? 'sortable' : ''}" data-hook data-sortable-link="#{@product.try(:id) ? update_positions_admin_product_product_properties_path(@product) : ''}")
          %thead
            %tr(data-hook="product_properties_header")
              %th
              %th #{ Spree::Property.model_name.human }
              %th #{ Spree::ProductProperty.human_attribute_name(:value) }
              %th.actions
          %tbody(id="product_properties" data-hook="product_properties")
            = f.fields_for :product_properties do |pp_form|
              = render 'spree/admin/product_properties/product_property_fields', f: pp_form, object_url: pp_form.object.try(:id) ? admin_product_product_property_path(@product.slug, pp_form.object.id) : nil
        = hidden_field_tag 'clear_product_properties', 'true'
        .pull-right
          %button(type='button' class='btn btn-secondary' onclick="addMoreProductPropertyRow()") More Property

      - if @product.id && !@product.deleted?
        = f.fields_for :variant_property_rules, @variant_property_rule do |rule_form|
          -#= rule_form.hidden_field 'id', value: @variant_property_rule.id
          = rule_form.hidden_field 'option_value_ids', value: @option_value_ids.to_a.join(',')
          - if @option_value_ids.present?
            %fieldset.no-border-top
              %table(class="index #{@product.try(:id) ? 'sortable' : ''}" data-hook data-sortable-link="#{ @product.try(:id) ? update_positions_admin_product_variant_property_rule_values_path(@product) : ''}")
                %thead
                  %tr(data-hook="variant_property_values_header")
                    %th
                    %th #{ Spree::Property.model_name.human }
                    %th #{ Spree::ProductProperty.human_attribute_name(:value) }
                    %th.actions
                %tbody#variant_property_values
                  = rule_form.fields_for :values do |values_form|
                    = render 'spree/admin/product_properties/product_property_fields', f: values_form, object_url: values_form.object.try(:id) ? admin_product_product_property_path(@product.slug, values_form.object.id) : nil
              - if can?([:create, :update], Spree::VariantPropertyRule)
                = render 'spree/admin/shared/edit_resource_links'

      %datalist#properties
        = safe_join @product.properties.map { |name| tag(:option, value: name) }

    %div(class="right col-3" data-hook="admin_product_form_right")

app/views/spree/admin/products/_new_product_image_row.html.haml
:ruby
  # Required locals:
  #   f: <FormBuilder>
  # Optional locals:
  #   index: <Integer> can be used as suffix to form input's ID
  #   row_id: <String>
  index = nil unless defined?(index)
  id_suffix = index ? "_#{index}" : ''
  row_id = 'new_product_image_row' unless defined?(row_id)
  style = 'display: none;' if row_id == 'new_product_image_row'
%tr(id="#{row_id}" class="product-image-row" style="#{style}")
  %td
    - if can?(:update_positions, Spree::Image)
      %span.handle
  %td
  %td
    - if @variants
      = f.select :image_viewable_ids, options_for_select(@variants), {}, name: "product[image_viewable_ids][]", id:"product_image_viewable_id#{id_suffix}", class:'fullwidth', autocomplete:'off'
  %td
    = f.text_field('image_alts', name: "product[image_alts][]", id:"product_image_alt#{id_suffix}")
  %td.actions
    - if can?(:create, Spree::Image)
      = f.file_field('uploaded_images', name: "product[uploaded_images][]", id:"product_uploaded_image#{id_suffix}")

app/views/spree/admin/products/_product_variant_row.html.haml
:ruby
  # Required locals:
  #   product
  #   variant
%tr(id="#{spree_dom_id variant}" data-hook="variants_row" class="#{ 'deleted' if variant.deleted? }")
  %td
    - if can? :update_positions, Spree::Variant
      %span.handle
  %td
    %table
      %tbody
        = fields_for variant do|vf|
          - @product.option_types.each do |option_type|
            %tr
              %td
                = vf.label 'option_value_ids', option_type.presentation
              %td
                = vf.collection_select 'option_value_ids', option_type.option_values,
                  :id, :presentation, { include_blank: true }, |
                  { name: 'variant[option_value_ids][]',  class: 'custom-select', |
                    id: "option_value_ids_#{option_type.presentation}" } |
    -#{variant.options_text }
  %td
    = fields_for variant do|vf|
      = vf.label(:price)
      = render 'spree/admin/shared/number_with_currency', f: vf, amount_attr: :price, currency: variant.default_price.currency
      %br/
      = vf.label :sku
      = vf.text_field(:sku)
  %td.actions
    - if can?(:update, variant)
      = link_to_with_icon 'check', t('spree.actions.save'), api_product_variant_path(product, variant), no_text: true, data: {action: 'save'}
      = link_to_with_icon 'cancel', t('spree.actions.cancel'), nil, no_text: true, data: {action: 'cancel'}
      = link_to_edit(variant, url: polymorphic_url([:edit, :admin, product, variant], host:'localhost' ), no_text: true) unless variant.deleted?
    - if can?(:destroy, variant)
      &nbsp;
      = link_to_delete(variant, url: polymorphic_url([:admin, product, variant], host:'localhost' ), no_text: true) unless variant.deleted?
  - if @product.variants.empty?
    %tr
      %td(colspan="4") #{ t('spree.none') }

app/views/spree/admin/products/erase.js.erb
$("#spree_product_<%= @product.id -%>").fadeOut();

app/views/spree/admin/products/index.html.erb
<% show_seller = spree_current_user.admin? && params[:user_id].nil?
-%>
<% admin_layout 'full-width' %>

<% admin_breadcrumb(plural_resource_name(Spree::Product)) %>

<% content_for :page_actions do %>
  <li>
    <%= link_to t('spree.new_product'), new_object_url, class: 'btn btn-primary' %>
  </li>
<% end if can?(:create, Spree::Product) %>

<% content_for :table_filter_title do %>
  <%= t('spree.search') %>
<% end %>

<% content_for :table_filter do %>
  <div data-hook="admin_products_sidebar">
    <%= search_form_for [:admin, @search] do |f| %>
      <%- locals = {f: f} %>
      <div class="row" data-hook="admin_products_index_search" >
        <div class="col-6">
          <div class="field">
            <%= f.label :name_cont, Spree::Product.human_attribute_name(:name) %>
            <%= f.text_field :name_cont, size: 15 %>
          </div>
        </div>

        <div class="col-4">
          <div class="field">
            <%= f.label :with_variant_sku_cont, Spree::Variant.human_attribute_name(:sku) %>
            <%= f.text_field :with_variant_sku_cont, size: 15 %>
          </div>
        </div>

        <div class="col-2">
          <div class="field checkbox">
            <label>
              <%= f.check_box :with_deleted, { checked: params[:q][:with_deleted] == 'true' }, 'true', 'false' %>
              <%= t('spree.show_deleted') %>
            </label>
          </div>
        </div>
      </div>

      <div class="actions filter-actions" data-hook="admin_products_index_search_buttons">
        <%= button_tag t('spree.search'), class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
<% end %>

<div id="new_product_wrapper" data-hook></div>

<%= paginate @collection, theme: "solidus_admin" %>

<% if @collection.any? %>
  <table class="index" id="listing_products">
    <colgroup>
      <col style="width: 15%;">
      <col style="width: 5%;">
      <col style="width: <%= show_seller ? 40 : 50 -%>%;">
      <col style="width: <%= show_seller ? 10 : 15 -%>%;">
      <% if show_seller -%><col style="width: 15%"><% end -%>
      <col style="width: 15%;">
    </colgroup>
    <thead>
    <tr data-hook="admin_products_index_headers">
      <th><%= Spree::Variant.human_attribute_name(:sku) %></th>
      <th></th>
      <th><%= sort_link @search,:name, Spree::Product.human_attribute_name(:name), { default_order: "desc" }, {title: 'admin_products_listing_name_title'} %></th>
      <th class="align-right"><%= sort_link @search,:master_default_price_amount, Spree::Product.human_attribute_name(:price), {}, {title: 'admin_products_listing_price_title'} %></th>
      <% if show_seller -%><th class="align-center">Seller</th><% end -%>
      <th data-hook="admin_products_index_header_actions" class="actions"></th>
    </tr>
    </thead>
    <tbody>
    <% @collection.each do |product| %>
      <tr <%== "style='color: red;'" if product.deleted? %> id="<%= spree_dom_id product %>" data-hook="admin_products_index_rows">
        <td><%= product.sku %></td>
        <td class="align-center">
          <%= render 'spree/admin/shared/image', image: product.gallery.images.first, size: :mini %>
        </td>
        <td><%= link_to product.try(:name), edit_admin_product_path(product) %>
          <br/><span class="text-muted"><%= product.variants.count -%> variants</span>
        </td>
        <td class="align-right"><%= product.display_price.to_html %></td>
        <% if show_seller -%>
        <td class="align-center"><%= link_to(product.user.username, admin_products_path(user_id: product.user_id), title: product.user_id ) if product.user -%></td>
        <% end -%>
        <td class="actions" data-hook="admin_products_index_row_actions">
          <%= link_to_edit product, no_text: true, class: 'edit' if can?(:edit, product) && !product.deleted? %>
          &nbsp;
          <%= link_to_clone product, no_text: true, class: 'clone' if can?(:clone, product) %>
          &nbsp;
          <%= link_to_delete product, no_text: true if can?(:delete, product) && !product.deleted? %>

          <%= link_to '', admin_erase_product_path(product), method: :delete, remote: true, class:'fa fa-eraser icon_link no-text', 'data-confirm' => 'Sure to permanently erase all related records and images?' if can?(:erase, product) %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="no-objects-found">
    <%= render 'spree/admin/shared/no_objects_found',
               resource: Spree::Product,
               new_resource_url: new_object_url %>
  </div>
<% end %>

<%= paginate @collection, theme: "solidus_admin" %>